services:
  postgres:
    image: postgres:16-alpine
    container_name: linky-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: linky
      POSTGRES_PASSWORD: linky
      POSTGRES_DB: linky
    volumes:
      - linky-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U linky -d linky"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
    linky-pg-data:
